imds = imageDatastore('.\Patch_biomarker\literatureData\normal',...
                      'IncludeSubfolders',true ,...
                      'LabelSource','foldernames'); 
imdsC = imageDatastore('.\Patch_biomarker\literatureData\cancer',...
            'IncludeSubfolders',true ,...
            'LabelSource','foldernames'); 
net = resnet18;
inputSize = net.Layers(1).InputSize;
pixelRange = [-30 30];
scaleRange = [0.9 1.1];
imageAugmenter = imageDataAugmenter( ...
    'RandXReflection',true, ...
    'RandXTranslation',pixelRange, ...
    'RandYTranslation',pixelRange, ...
    'RandXScale',scaleRange, ...
    'RandYScale',scaleRange);
augimds = augmentedImageDatastore(inputSize(1:2),imds, ...
    'DataAugmentation',imageAugmenter);
augimdsC= augmentedImageDatastore(inputSize(1:2),imdsC,...
          'DataAugmentation',imageAugmenter);
layer = 'pool5';
featuresN = activations(net,augimds,layer,'OutputAs','rows');
featuresC = activations(net,augimdsC,layer,'OutputAs','rows');
save('.\Patch_biomarker\literaturemodelfeatures\literDLfeatures (2)\normal\GapNet-PL.mat','featuresN','imds');
save('.\Patch_biomarker\literaturemodelfeatures\literDLfeatures (2)\cancer\GapNet-PL.mat','featuresC','imdsC');